CovarianceBlock and associated MetaData
njoy/codex pull request #3
Opened 2023-04-04 09:16 UTC by whaeck

This PR introduces the CovarianceBlock and its associated MetaData. 

In general, we would have covariance data given as follows:
```
      N1,R1 N1,R2 N2,R1 ...
N1,R1   A     B     C    ...
N1,R2   B     D     E    ...
N2,R1   C     E     F    ...
...
```

A CovarianceBlock represents a piece of this data, corresponding to a single one of these matrices A, B, C, etc. The MetaData contains the information associated to the rows (and columns) of the block in question. The meta data is currently limited to the following:
- the nuclide and reaction the rows and columns are associated to
- the energy structure of the rows and columns

For a block on the diagonal (row and column metadata are the same) only the row metadata is stored internally (using std::optional). Such a diagonal block will be inherently represented by a square matrix. Off-diagonal blocks do not necessarily have to be square.

As such, these objects are currently only usable for covariance data directly associated to reaction data (i.e. MF31, MF33). While MF34 and MF35 data will fit in these, we'll need to expand the meta data object to contain additional information (i.e. the MF35 data needs the incident energy group for the covariance block). Resonance covariance data is another beast altogether and does not fit in these objects. Because of this, we may want to rename the CovarianceBlock to ReactionCovarianceBlock instead and create a ResonanceCovarianceBlock for resonance parameters themselves. 

Current shortcomings:
- we do not store whether or not the covariances are relative or absolute
- for things like angular distribution covariances, we need to store the reference frame

2023-04-11 16:53 UTC, ptalou commented on src/codex/MetaData/test/MetaData.test.cpp
When throwing an exception after testing the energies for identical adjacent values, could you put out the energies in the message?

2023-04-11 17:12 UTC, ptalou commented on src/codex/MetaData/src/verifyEnergies.hpp
This function should be made static.

2023-04-11 18:04 UTC, ptalou requested changes
Good work!

2023-04-11 18:04 UTC, ptalou commented on src/codex/MetaData/test/MetaData.test.cpp
> +      std::vector< double > wrong = { 2e+7, 1., 1., 1e-5 };
Those energies are not sorted, so the test will not check the adjacent values but fail before.

2023-04-11 18:04 UTC, ptalou commented on src/codex/CovarianceBlock/src/verifyMatrix.hpp
> +void verifyMatrix( const Matrix< double >& matrix,
Even in the case of a square matrix block, on the diagonal of the full matrix, one needs to check that this matrix block is symmetric.

2023-04-11 18:04 UTC, ptalou commented on src/codex/CovarianceBlock/src/verifyMatrix.hpp
> +  // check if the matrix row order is consistent with the energy boundaries
Same error message. Could be combined or specific for rows and columns, respectively.

2023-04-11 18:04 UTC, ptalou commented on src/codex/CovarianceBlock/src/ctor.hpp
> +CovarianceBlock( MetaData row, MetaData column, Matrix< double > matrix ) :
I don't like the labels 'row' and 'column' for the metadata... maybe 'metadata_row'?

2023-04-11 18:04 UTC, ptalou commented on src/codex/CovarianceBlock/src/ctor.hpp
> + *  @param[in] metadata   the metadata associated with the covariance block
The documentation does not correspond to the arguments (copy/paste?)

2023-04-11 18:04 UTC, ptalou commented on src/codex/CovarianceBlock/test/CovarianceBlock.test.cpp
> +          "for an off-diagonal covariance block (rows)" ) {
replace "covariance block (rows)" by "covariance block (columns)"

2023-04-11 18:04 UTC, ptalou commented on python/src/CovarianceBlock.python.cpp
> +    "row",
Change to row_metadata?

2023-04-11 18:04 UTC, ptalou commented on python/src/CovarianceBlock.python.cpp
> +    python::return_value_policy::reference_internal
Maybe a word or two of explanation here?

2023-04-11 18:51 UTC, whaeck commented on src/codex/MetaData/test/MetaData.test.cpp
> +      std::vector< double > wrong = { 2e+7, 1., 1., 1e-5 };
Good find. The Python test is correct though, weird.

2023-04-11 18:52 UTC, whaeck commented on src/codex/CovarianceBlock/src/verifyMatrix.hpp
> +void verifyMatrix( const Matrix< double >& matrix,
Indeed. I actually added the symmetry test in a future PR so I will not address it here.

2023-04-12 22:18 UTC, ptalou approved these changes

2023-04-12 22:21 UTC, merged