Calculation of eigenvalues
njoy/codex pull request #7
Opened 2023-04-07 07:27 UTC by whaeck

Added the capability to calculate eigenvalues for diagonal covariance blocks.

Added a test to verify the symmetric nature of the covariance matrix in a diagonal covariance block. This is needed to exploit the cpability of the SelfAdjointEigenSolver from Eigen (eigenvalue solver for symmetric matrices). If the matrix is not symmetric at construction, an exception will be thrown.

Possible shortcoming and potential improvements:
- A = A^T test for symmetry should use floating point comparison (look for approximate comparison option in Eigen)
- add convenience test functions for general matrices

2023-04-18 21:05 UTC, ptalou requested changes

2023-04-18 21:05 UTC, ptalou commented on python/src/matrix.python.cpp
> + *  @brief Wrap a BasicBidirectionalAnyView templated on the Element type
What does that mean?! No, really!!

2023-04-18 21:05 UTC, ptalou commented on src/codex.hpp
> +// covariance matrix components
Should you include #include "matrix.hpp" as well?

2023-04-19 15:06 UTC, whaeck commented
Changes are in update/reviews

2023-04-19 19:49 UTC, ptalou approved these changes

2023-04-19 19:50 UTC, merged